#!/bin/bash

# Session Cleanup Helper Script
# Use this during development to clear browser sessions

echo ""
echo "🧹 Yacht Sentinel AI - Session Cleanup Helper"
echo "=============================================="
echo ""
echo "This script helps you clear browser sessions during development."
echo ""
echo "📋 OPTION 1: Clear via Browser Console"
echo "   1. Open your browser to http://localhost:5173"
echo "   2. Press F12 to open DevTools"
echo "   3. Go to Console tab"
echo "   4. Paste this command:"
echo ""
echo "   localStorage.clear(); sessionStorage.clear(); location.reload();"
echo ""
echo ""
echo "📋 OPTION 2: Clear via Browser DevTools"
echo "   1. Press F12 to open DevTools"
echo "   2. Go to Application tab (Chrome) or Storage tab (Firefox)"
echo "   3. Click 'Local Storage' → Select your site"
echo "   4. Right-click → 'Clear'"
echo "   5. Do the same for 'Session Storage'"
echo "   6. Refresh the page (F5)"
echo ""
echo ""
echo "📋 OPTION 3: Use Incognito/Private Mode"
echo "   - Chrome: Cmd+Shift+N (Mac) or Ctrl+Shift+N (Windows)"
echo "   - Firefox: Cmd+Shift+P (Mac) or Ctrl+Shift+P (Windows)"
echo "   - Safari: Cmd+Shift+N"
echo ""
echo "   This starts fresh with no saved sessions."
echo ""
echo ""
echo "🔑 Login Credentials:"
echo "   Email: superadmin@yachtexcel.com"
echo "   Password: admin123"
echo ""
echo "✅ Session should now be cleared. Reload the app to login fresh."
echo ""
